version: '3'
services:
  dey4.0:
    restart: always
    user: dey
    image: peyoot/dey:dey-4.0-r3
    container_name: dey4.0
#    ports:
#      - "21:21"
#    environment:
#      - DEY-MIRROR_URL=dey-mirror.eccee.com
#      - DEY-MIRROR_PORT=1080
    volumes:
      - ./workspace:/home/dey/workspace:rw
      - ../meta-custom:/usr/local/dey-4.0/sources/meta-custom
    entrypoint:
#      - bash
      - /home/dey/docker-entrypoint.sh
networks:
  default:
    external:
      name: pvpn
