version: '3'
services:
  dey3.2:
    restart: always
    user: dey
    image: digidotcom/dey:dey-3.2-r2
    container_name: dey3.2
#    ports:
#      - "21:21"
#    environment:
#      - DEY-MIRROR_URL=dey-mirror.eccee.com
#      - DEY-MIRROR_PORT=1080
    volumes:
      - ./workspace:/home/dey/workspace:rw
    entrypoint:
#      - bash
      - /home/dey/docker-entrypoint.sh
networks:
  default:
